name: Deploy preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci --ignore-scripts
      - run: npm run build
        env:
          NODE_ENV: production
          VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
          VITE_CONTACT_EMAIL: ${{ vars.VITE_CONTACT_EMAIL }}
          VITE_CTA_URL: ${{ vars.VITE_CTA_URL }}
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: main
          umbrella-dir: preview
          custom-url: ${{ vars.VITE_BASE_URL }}
