name: Deploy website

on: pull_request

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci --ignore-scripts
      - run: npm run build
        env:
          NODE_ENV: production
          VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
          VITE_CONTACT_EMAIL: ${{ vars.VITE_CONTACT_EMAIL }}
          VITE_CTA_URL: ${{ vars.VITE_CTA_URL }}
          VITE_INDEXING: ${{ vars.VITE_INDEXING }}
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
        with:
          preview: true